### PR TITLE
Only warn once when a flag is missing

### PR DESCRIPTION
**Pull request by erbridge**
It's totally legitimate to reference a feature flag that doesn't exist, yet, but before this change, doing so would spam our logs with warnings.

### CODE REVIEW

**Comment by philandstuff** [comment]
Hmm, I think it might be a useful signal that a flag has been typoed? It does mean we need to remember to create the flag before deploying though, otherwise we get said spam.

**Comment by erbridge** [comment]
Has that ever happened for us? Because I know we do get it right, but don't create the flag in LaunchDarkly.

**Comment by nickstenning** [comment]
IMO most ergonomic thing to do here would be to keep a package private `map[string]bool` which says whether or not we've emitted the warning, and emit it once before setting the key value to `true` in that map.

**Comment by erbridge** [comment]
Nice. I like that idea.

**Comment by philandstuff** [comment]
as long as said map is thread-safe. A sync.Map, say.

**Review by philandstuff — APPROVED** [review]

**Pull request merged**
